"use client";
import {useMemo,useState} from "react";

const products=[
{id:1,name:"Paracetamol 500 mg 10 Tablet",cat:"Obat",price:12500,icon:"💊",rating:"4.9"},
{id:2,name:"Vitamin C 1000 mg 10 Tablet",cat:"Vitamin",price:25000,icon:"🟠",rating:"4.8"},
{id:3,name:"Strepsils Honey & Lemon 8 Tablet",cat:"Obat",price:32500,icon:"🍯",rating:"4.9"},
{id:4,name:"Cetaphil Gentle Skin Cleanser 250 ml",cat:"Perawatan Pribadi",price:115000,icon:"🧴",rating:"4.9"},
{id:5,name:"Omron Tensimeter HEM-7121",cat:"Alat Kesehatan",price:420000,icon:"🩺",rating:"4.9"},
{id:6,name:"Minyak Telon 60 ml",cat:"Ibu & Anak",price:28000,icon:"👶",rating:"4.8"}];
const cats=[["Obat","💊"],["Vitamin","🧴"],["Ibu & Anak","👶"],["Perawatan Pribadi","🧼"],["Alat Kesehatan","🩺"],["Herbal","🌿"]];
const rupiah=n=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n);

export default function Home(){
 const[q,setQ]=useState(""); const[cat,setCat]=useState("Semua"); const[cart,setCart]=useState([]); const[consult,setConsult]=useState(false); const[checkout,setCheckout]=useState(false); const[done,setDone]=useState("");
 const shown=useMemo(()=>products.filter(p=>(!q||p.name.toLowerCase().includes(q.toLowerCase())||p.cat.toLowerCase().includes(q.toLowerCase()))&&(cat==="Semua"||p.cat===cat)),[q,cat]);
 const count=cart.reduce((a,b)=>a+b.qty,0), total=cart.reduce((a,b)=>a+b.qty*b.price,0);
 const add=p=>setCart(v=>{const e=v.find(x=>x.id===p.id);return e?v.map(x=>x.id===p.id?{...x,qty:x.qty+1}:x):[...v,{...p,qty:1}]});
 const order=e=>{e.preventDefault();setDone("KO-"+Date.now().toString().slice(-8));setCart([])};
 return <main>
  <header><div className="wrap nav"><a className="brand" href="#"><b>✚</b><span>KlikObat<em>.com</em><small>by Farmabox</small></span></a><nav><a href="#">Beranda</a><a href="#produk">Cari Obat</a><a href="#kategori">Kategori</a><button onClick={()=>setConsult(true)}>Konsultasi Apoteker</button><a href="#promo">Promo</a><a href="#artikel">Artikel Kesehatan</a></nav><div className="actions"><button className="cart" onClick={()=>setCheckout(true)}>🛒<i>{count}</i></button><button className="ghost">Masuk</button><a className="primary" href="#member">Daftar</a></div></div></header>
  <section className="hero"><div className="wrap heroGrid"><div><p className="eyebrow">SEHAT LEBIH DEKAT, HIDUP LEBIH BAIK</p><h1>Pesan Obat & Produk Kesehatan <span>Lebih Mudah</span></h1><p className="lead">Cari, pesan, dan terima obat serta produk kesehatan dengan alur yang sederhana, cepat, dan mudah dipahami.</p><div className="search"><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Cari obat, vitamin, atau masalah kesehatan..."/><a href="#produk">Cari</a></div><div className="chips"><span>Contoh pencarian:</span><button onClick={()=>setQ("Paracetamol")}>Paracetamol</button><button onClick={()=>setQ("Vitamin")}>Vitamin C</button><button onClick={()=>setQ("Strepsils")}>Obat Batuk</button></div></div><div className="scene"><div className="doc">👩🏻‍⚕️</div><div className="phone"><b>KlikObat.com</b><div>Cari obat...</div><p>💊 🧴 👶</p><strong>Sehat setiap hari dimulai di sini</strong></div><div className="bike">🛵<small>Pesanan sampai lebih cepat</small></div><div className="note">Sehat<br/>Itu Mudah<br/>Bersama<br/><b>KlikObat.com</b></div></div></div></section>
  <section className="wrap trust"><div>🛡️ <b>Obat Asli</b><span>Produk kesehatan terkurasi</span></div><div>👨‍⚕️ <b>Konsultasi Apoteker</b><span>Alur chat konsultasi demo</span></div><div>🚚 <b>Pengiriman Cepat</b><span>Simulasi order sampai rumah</span></div><div>🔒 <b>Aman & Terpercaya</b><span>Tanpa pembayaran riil di MVP</span></div></section>
  <section id="kategori" className="wrap section"><div className="title"><h2>Kategori Produk</h2><button onClick={()=>setCat("Semua")}>Lihat Semua ›</button></div><div className="categories">{cats.map(([n,i])=><button key={n} className={cat===n?"active":""} onClick={()=>setCat(n)}><strong>{i}</strong><b>{n}</b><span>{n==="Obat"?"Obat bebas & resep dokter":n==="Vitamin"?"Dukung daya tahan tubuh":n==="Ibu & Anak"?"Untuk keluarga tercinta":n==="Perawatan Pribadi"?"Tampil sehat setiap hari":n==="Alat Kesehatan"?"Untuk hidup lebih nyaman":"Solusi alami untuk sehat"}</span></button>)}</div></section>
  <section className="wrap content section"><div id="produk"><div className="title"><h2>Produk Pilihan</h2><span>{shown.length} produk</span></div><div className="products">{shown.map((p,idx)=><article key={p.id}>{idx===0&&<label>Best Seller</label>}<div className="pic">{p.icon}</div><h3>{p.name}</h3><div className="price">{rupiah(p.price)}</div><small>★ {p.rating} (demo)</small><button onClick={()=>add(p)}>+ Keranjang</button></article>)}</div>{!shown.length&&<div className="empty">Produk tidak ditemukan. Coba kata kunci lain.</div>}</div><aside><div className="consult"><div className="avatar">👩🏻‍⚕️</div><div><h2>Konsultasi Apoteker</h2><p>Punya pertanyaan tentang obat, dosis, atau produk kesehatan? Mulai simulasi chat konsultasi.</p><button className="primary" onClick={()=>setConsult(true)}>Mulai Konsultasi</button></div></div><div className="steps"><h2>Cara Pesan di KlikObat.com</h2><div><span><b>1</b>🔎<small>Cari Produk</small></span><span><b>2</b>🛒<small>Pesan</small></span><span><b>3</b>🏠<small>Dikirim</small></span><span><b>4</b>✅<small>Selesai</small></span></div></div></aside></section>
  <section id="member" className="wrap member"><div><h2>Gabung Member KlikObat.com</h2><p>Dapatkan akses lebih cepat ke fitur belanja dan konsultasi pada pengembangan berikutnya.</p></div><div>◉ Riwayat belanja &nbsp; ◉ Info promo &nbsp; ◉ Akses konsultasi</div><button>Daftar Sekarang</button></section>
  <section id="artikel" className="wrap section"><div className="title"><h2>Artikel Kesehatan</h2><button>Lihat Semua Artikel ›</button></div><div className="articles"><article>🌤️ <span><b>Tips Menjaga Daya Tahan Tubuh di Musim Pancaroba</b><small>5 menit baca</small></span></article><article>🍊 <span><b>Panduan Memilih Vitamin yang Tepat untuk Keluarga</b><small>4 menit baca</small></span></article><article>📋 <span><b>Cara Aman Mengonsumsi Obat dengan Benar</b><small>6 menit baca</small></span></article></div></section>
  <footer><div className="wrap foot"><div><div className="brand"><b>✚</b><span>KlikObat<em>.com</em><small>by Farmabox</small></span></div><p>Solusi Kesehatan Keluarga Indonesia</p></div><div><b>Tentang Kami</b><span>Profil Perusahaan</span><span>Karir</span><span>Blog Kesehatan</span></div><div><b>Layanan</b><span>Cari Obat</span><span>Konsultasi Apoteker</span><span>Pengiriman</span></div><div><b>Hubungi Kami</b><span>0800 1 566 622</span><span>cs@klikobat.com</span><span>08.00 - 22.00 WIB</span></div></div><div className="copy">© 2026 KlikObat.com by Farmabox. MVP v0.1</div></footer>
  {consult&&<div className="modal"><div className="dialog"><button className="close" onClick={()=>setConsult(false)}>×</button><p className="eyebrow">KONSULTASI APOTEKER</p><h2>Chat Konsultasi MVP</h2><div className="chat"><p>👩🏻‍⚕️ Halo, silakan tulis pertanyaan umum tentang obat atau produk kesehatan.</p><p className="me">Saya ingin bertanya tentang obat yang aman digunakan.</p><p>👩🏻‍⚕️ Pada MVP ini chat belum terhubung ke apoteker sungguhan. Fitur ini akan dikembangkan pada versi berikutnya.</p></div><div className="notice">Untuk kondisi darurat atau gejala berat, gunakan layanan medis langsung.</div><button className="primary wide" onClick={()=>setConsult(false)}>Tutup</button></div></div>}
  {checkout&&<div className="modal"><div className="dialog checkout"><button className="close" onClick={()=>{setCheckout(false);setDone("")}}>×</button>{done?<><div className="ok">✓</div><h2>Order demo berhasil dibuat</h2><p>Nomor order: <b>{done}</b></p><div className="notice">Tidak ada pembayaran atau pesanan obat riil pada MVP ini.</div></>:<><p className="eyebrow">CHECKOUT MVP</p><h2>Keranjang ({count})</h2>{cart.length? <><div className="cartlist">{cart.map(x=><div key={x.id}><span>{x.qty}× {x.name}</span><b>{rupiah(x.qty*x.price)}</b></div>)}</div><div className="total"><span>Total sementara</span><b>{rupiah(total)}</b></div><form onSubmit={order}><input required placeholder="Nama penerima"/><input required placeholder="Nomor WhatsApp"/><textarea required rows="3" placeholder="Alamat pengiriman"/><button className="primary wide">Buat Order Demo</button></form></>:<div className="empty">Keranjang masih kosong.</div>}</>}</div></div>}
 </main>
}